tenzir/threatbus

.github/workflows/python-egg.yml
.gitignore
README.md
plugins/apps/threatbus-misp/README.md
plugins/apps/threatbus-misp/setup.py
plugins/apps/threatbus-zeek/README.md
plugins/apps/threatbus-zeek/setup.py
plugins/backbones/threatbus-inmem/README.md
plugins/backbones/threatbus-inmem/setup.py
setup.cfg
setup.py

- Automatically publish on PyPI when `git tag`s are pushed.
- Add/improve readme files for all plugins

Automate PyPI distribution

---

plugins/backbones/threatbus_inmem/setup.py
setup.py

Remove unused imports that slipped the last code review.

Remove unused imports

---

README.md

Add two simple examples for using Threat Bus with Docker.

Update Readme to cover Docker usage

---

Dockerfile_integration
Makefile
lgtm.yml
tests/integration/test_misp_zeek_inmem.py
tests/utils/kafka_receiver.py
threatbus/__init__.py

- Fix integration test, such that it not uses MISP
- Add `tests/utils` to sources monitored by `LGTM`
- Address `LGTM` warnings

Improve LGTM scores

---

plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/backbones/threatbus_inmem/setup.py
setup.py

Update release version for Threat Bus and all plugins.

Set new calver version for threatbus and plugins

---

.gitignore
apps/vast/vast-bridge.py

This PR feature-completes the VAST bridge and enables it to correctly forward IoC removals to VAST.

Handle IoC removal in VAST bridge

---

config.yaml
plugins/apps/threatbus_cif3/plugin.py
plugins/apps/threatbus_zeek/plugin.py

- Align the information logged at plugin start up
- Make CIF API configuration mandatory
- Add CIF plugin config snip to `config.yaml` in main folder

Align Plugins

---

README.md
apps/vast/README.md
apps/vast/requirements.txt

This PR brings a couple of README improvements. The snapshot request feature is now described with positive integers.

Use positive integers for Snapshot Requests

---

CHANGELOG.md
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

This prepares the repository for the October 2020 release. The merge commit of this PR is the one to be tagged for release.
n/t
Once this PR is merged, we can finally merge the documentation changes for the `zmq-app` plugin: https://github.com/tenzir/event-horizon/pull/671

Prepare repository for October 2020 release

---

Makefile

Continue cleaning even when errors occur.

Continue clean target on error

---

Dockerfile
plugins/apps/threatbus_misp/setup.py

This fixes the Docker build.
```
cp config.yaml.example config.yaml  
docker build . -t tb
docker run --net=host -ti tb
```
It will behave like a normal process, can be terminated with `ctrl+c` and updates logs to the terminal when you send around messages. The `--net=host` makes it work with locally installed software like misp, cif, or vast.

Use pip to install packages

---

CHANGELOG.md
apps/vast/CHANGELOG.md
plugins/backbones/file_benchmark/setup.py

Rotate CHANGELOG, bump a missing version.

Prepare November Release

---

apps/vast/CHANGELOG.md
apps/vast/config.yaml.example
apps/vast/pyvast_threatbus/pyvast_threatbus.py

Enable file logging via config section.
File-by-file.
Verify that the app starts either with `--loglevel` or a properly configured `logging` section in the `config.yaml`

Enable file logging via config section

---

CHANGELOG.md
apps/vast/pyvast_threatbus/pyvast_threatbus.py
systemd/README.md
systemd/pyvast-threatbus.service
systemd/threatbus.service

Add systemd units and readme.
- Install Threat Bus + `pyvast-threatbus` on your *Linux machine* via `pip`
- Follow the instructions in `systemd/README` to setup both service units
- Start Threat Bus / `pyvast-threatbus` via `systemctl start`, confirm that it works as expected

Add systemd units

---

tests/utils/misp-ioc-sender/misp-ioc-sender.py

Add shebang to MISP ioc sender

---

plugins/apps/threatbus_misp/threatbus_misp/plugin.py

Log errors when the MISP plugin fails to upload sightings.

Log errors from sighting report

---

CHANGELOG.md
apps/vast/CHANGELOG.md
apps/vast/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

- Bump all versions for PyPI releases
- Rotate changelogs

Prepare December Release

---

plugins/apps/threatbus_misp/README.md

Update instructions to run MISP in local VM

---

CHANGELOG.md
apps/vast/CHANGELOG.md
apps/vast/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py

Rotate changelogs and bump versions / dependencies.
file-by-file

Prepare Repository for March Release

---

README.md

Make the README look / read nicer.
proof read.

Update README with OpenCTI integration

---

CHANGELOG.md
README.md

We're switching from EMS to Gitter, so let's make it official.
File-by-file.

Update chat URL in README

---

CHANGELOG.md
README.md
apps/vast/CHANGELOG.md
apps/vast/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

Prepare April Release

---

CHANGELOG.md
plugins/apps/threatbus_zmq_app/threatbus_zmq_app/plugin.py

Fix bug in SnapshotRequest handling

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/vast/CHANGELOG.md
apps/vast/setup.py
apps/zmq-app-template/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

Prepare May Release

---

README.md

We now use a CNAME redirect.
Just look/try.

Simplify Slack URL

---

CHANGELOG.md

Fix forgotten URL in changelog

---

.github/workflows/python-egg.yml
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/Dockerfile
apps/stix-shifter/README.md
apps/vast/CHANGELOG.md
apps/vast/Dockerfile
apps/vast/README.md

Add Dockerfiles for `pyvast-threatbus` and `stix-shifter-threatbus`.
File-by-file.
Try the commands from the README.

Add Dockerfiles for ZMQ Apps

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/suricata/CHANGELOG.md
apps/suricata/setup.py
apps/vast/CHANGELOG.md
apps/vast/Dockerfile
apps/vast/setup.py
apps/zmq-app-template/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

Bump version numbers & rotate changelogs.
n/t

June Release

---

apps/suricata/suricata_threatbus/suricata.py

Fix a copy & paste error. No changelog entry needed imo.

Fix env prefix for suricata app

---

Makefile
apps/stix-shifter/stix_shifter_threatbus/shifter.py
apps/suricata/suricata_threatbus/suricata.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/zmq-app-template/zmq_app_template/template.py
requirements.txt
setup.py

- Pin a stix-shifter dependency
- Add suricata app to Makefile
- Fix missing quotes
n/t

Minor fixups

---

apps/stix-shifter/stix_shifter_threatbus/shifter.py
apps/suricata/suricata_threatbus/suricata.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/zmq-app-template/zmq_app_template/template.py

Fix off-by-one error in the hostname determination.
n/t

Fix off-by-one error

---

README.md

Document that threatbus requires at least python3.7

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/suricata/CHANGELOG.md
apps/suricata/setup.py
apps/vast/CHANGELOG.md
apps/vast/setup.py
apps/zmq-app-template/setup.py
docker/pyvast-threatbus/Dockerfile
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

- Rotate CHANGELOGs for July Release
- Bump VAST dependency in Dockerfile
- Bump all versions for June release

July Release

---

.github/workflows/python-egg.yml

In addition to latest and versioned releases this adds per-commit uploads for every commit to master.
Verify that my usage of https://github.com/elgohr/Publish-Docker-Github-Action is correct.

Upload tenzir/threatbus:${sha} to Docker Hub

---

tests/utils/misp-ioc-sender/misp-ioc-sender.py

Rename the last instance of PYVAST_THREATBUS -> VAST_THREATBUS

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/suricata/CHANGELOG.md
apps/suricata/setup.py
apps/vast/setup.py
apps/zmq-app-template/setup.py
docker/vast-threatbus/Dockerfile
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

Update threatbus version for the November release.

Prepare repository for 2021.11.18 release

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/suricata/CHANGELOG.md
apps/suricata/setup.py
apps/vast/CHANGELOG.md
apps/vast/setup.py
apps/vast/vast_threatbus/vast_threatbus.py
apps/zmq-app-template/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

This fixes the low-priority check, and prepares for a hot fix release.
Verify that I got all the version numbers right, and also verify that the low-priority check works as expected. I can show the latter in a quick video call if that makes it easier.

Fix check for `--low-priority` flag

---

README.md

The OpenCTI-Platform/connectors structure has changed so this link needed updating. Thank you! 😄

Update link to OpenCTI connector

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/suricata/CHANGELOG.md
apps/suricata/setup.py
apps/vast/CHANGELOG.md
apps/vast/setup.py
apps/zmq-app-template/setup.py
docker/vast-threatbus/Dockerfile
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

The usual monthly changelog rotation.

Prepare repository for Threat Bus 2021.12.16

---

apps/vast/vast_threatbus/vast_threatbus.py

Also check for return code when running the sighting context transform. Closes #185.
Should be trivial.

Check for return code when running transform process

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/suricata/CHANGELOG.md
apps/suricata/setup.py
apps/vast/CHANGELOG.md
apps/vast/setup.py
apps/zmq-app-template/setup.py
docker/vast-threatbus/Dockerfile
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

Prepare Threat Bus and apps for 2022.01.27 release
