README.md

I enabled LGTM static code analysis and we have 0 alerts / code quality A+.
This PR adds the two respective LGTM badges to the README.

Enable LGTM for Threat Bus

---

.github/workflows/python-egg.yml
Dockerfile

- Remove unused keyword from `twine upload` step that made the build step fail.
- Copy readme in Docker container

Fix build workflow

---

.github/workflows/python-egg.yml

Following the new naming convention, GitHub releases will be named "Threat Bus YYYY-mm-dd"
PyPI releases will be named after the Git tag.

Use calendar versioning for GitHub releases

---

.github/workflows/python-egg.yml
Dockerfile

CI step to build a `threatbus` image and push to the public `tenzir` DockerHub registry. 
See also [test run for the upload](https://github.com/tenzir/threatbus/runs/415470526?check_suite_focus=true#step:4:1) or try `docker run tenzir/threatbus:story-ch12293 -c config.yaml`.

Add CI step to publish Docker image

---

.github/workflows/python-egg.yml
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/backbones/threatbus_inmem/setup.py
setup.py

- After GitHub release has been written + published manually, the action will pick it up and publish artifacts to it
- PyPI versioning now uses CalVer schema

Switch to Manual Release-Workflow with Calendar Versioning

---

plugins/apps/threatbus_vast/message_mapping.py
plugins/apps/threatbus_vast/plugin.py

With the new matcher implementation of VAST we can now report back the sightings of IoCs to Threat Bus.
This PR addresses the two respective `TODOs` such that VAST sightings are now understood by Threat Bus.

Report VAST sightings back to Threat Bus

---

CHANGELOG.md
config.yaml.example
plugins/apps/threatbus_misp/README.md
plugins/apps/threatbus_misp/message_mapping.py
plugins/apps/threatbus_misp/plugin.py
plugins/apps/threatbus_misp/test_message_mapping.py

This PR adds a whitelist-filtering mechanism to the MISP plugin. Administrators can define desired properties of IoCs (MISP attributes) in the configuration, and the plugin will forward only those IoCs to Threat Bus that match the configured properties.
The filter is implemented for IoCs that are received via ZeroMQ / Kafka as well as IoCs that are queried as part of a snapshot.

Add Whitelist-Filter for IoCs to MISP plugin

---

apps/vast/message_mapping.py
apps/vast/test_message_mapping.py

The bridge wrongly assumed that all timestamp fields in VAST results would be named `ts`. Now, the bridge additionally supports fields named `timestamp`.

Handle two common timestamp field names

---

apps/vast/vast-bridge.py

Instead of splitting provided cmd arguments plainly on spaces, this change proposes to perform a lexicographical split.

Split commands lexicographically

---

CHANGELOG.md
plugins/apps/threatbus_misp/plugin.py

The MISP plugin can now be started without the need to configure a valid `api` connection. If the configuration is present, it is checked for validity (as before). If omitted, the plugin can still receive attribute updates from MISP via ZMQ or Kafka, but it cannot report back Sightings or execute Snapshot requests.

Allow startup without API connection

---

apps/vast/README.md
apps/vast/config.yaml.example
apps/vast/requirements.txt
apps/vast/vast-bridge.py

The `vast-bridge.py` can now be configured with a `config.yaml` file or via command-line arguments.

Add config file support to vast-bridge.py

---

CHANGELOG.md
Makefile
apps/vast/vast-bridge.py
plugins/apps/threatbus_zmq_app/README.md
plugins/apps/threatbus_zmq_app/message_mapping.py
plugins/apps/threatbus_zmq_app/plugin.py
plugins/apps/threatbus_zmq_app/test_message_mapping.py
tests/integration/test_zmq_app_management.py

- Add heatbeat feature to `zmq-app` plugin.
- Implement heartbeats in `vast-bridge`
- Reconnect `vast-bridge` on heartbeat failure
Commit-by-commit

ZMQ-App Heartbeats & vast-bridge reconnect handling

---

apps/vast/message_mapping.py
apps/vast/test_message_mapping.py

This PR depends on https://github.com/tenzir/vast/pull/1161
Rewrite suffix-based VAST queries to concept queries instead.

Use concept queries over suffix queries

---

CHANGELOG.md
apps/vast/CHANGELOG.md
apps/vast/config.yaml.example
apps/vast/message_mapping.py
apps/vast/pyvast_threatbus.py
apps/vast/test_message_mapping.py
plugins/apps/threatbus_cif3/message_mapping.py
plugins/apps/threatbus_cif3/plugin.py
plugins/apps/threatbus_misp/plugin.py
plugins/apps/threatbus_zeek/plugin.py
plugins/apps/threatbus_zmq_app/plugin.py
plugins/backbones/threatbus_inmem/plugin.py
plugins/backbones/threatbus_rabbitmq/__init__.py
plugins/backbones/threatbus_rabbitmq/helpers.py
plugins/backbones/threatbus_rabbitmq/plugin.py
plugins/backbones/threatbus_rabbitmq/rabbitmq_consumer.py
plugins/backbones/threatbus_rabbitmq/rabbitmq_publisher.py
plugins/backbones/threatbus_rabbitmq/test_helpers.py
tests/integration/test_message_roundtrips.py
tests/integration/test_rabbitmq.py
tests/integration/test_zeek_app.py
tests/integration/test_zmq_app_management.py
tests/utils/rabbitmq_sender.py
tests/utils/zmq_receiver.py
threatbus/__init__.py
threatbus/appspecs.py
threatbus/backbonespecs.py
threatbus/data.py
threatbus/stoppable_worker.py
threatbus/threatbus.py

Improve (retro-matching) performance.
- use asynchronous tasks to query VAST concurrently
- add configurable `ulimit` to control task count
- use [multiprocessing.JoinableQueue](https://docs.python.org/3.8/library/multiprocessing.html#multiprocessing.JoinableQueue) for message passing
- use `select` system call (possible via JoinableQueue) to speed up message distribution
- add `StoppableWorker` base-class for background threads
- control shutdown behavior of plugins
*File-by-file.*
Test this as follows:
- setup a virtual environment, somewhere on your computer, via `virtualenv venv`
- activate it `source venv/bin/activate`
- run `make dev-mode`
- write a config that activates all plugins (install broker, CIF, MISP, RabbitMQ ... locally first, see READMEs)
- run Threat Bus via …

Improve message distribution performance

---

CHANGELOG.md
apps/zeek/threatbus.zeek

This PR fixes an issue where the Zeek app fails to initiate a connection to Threat Bus when running in cluster mode.
In one shot.

Fix Zeek app in cluster mode

---

plugins/apps/threatbus_cif3/threatbus_cif3/plugin.py
plugins/apps/threatbus_misp/threatbus_misp/plugin.py
plugins/apps/threatbus_zeek/threatbus_zeek/plugin.py
plugins/apps/threatbus_zmq_app/threatbus_zmq_app/plugin.py
plugins/backbones/threatbus_inmem/threatbus_inmem/plugin.py
plugins/backbones/threatbus_rabbitmq/threatbus_rabbitmq/plugin.py
threatbus/stoppable_worker.py
threatbus/threatbus.py

This PR fixes a bug that was introduced with https://github.com/tenzir/threatbus/pull/61
This bug caused Threat Bus to terminate directly after startup in Python 3.7.3 and earlier. A detailed description of the issue can be found in this [Stackoverflow post](https://stackoverflow.com/questions/64917285/difference-in-python-thread-join-between-python-3-7-and-3-8).
*Not needed*: This fixes an *unreleased* bug and a Changelog entry for the desired behavior already exists.
Commit-by-commit
Test this as follows:
- you need two Python installations, 3.7 <= Python <= 3.7.3 and Python >= 3.7.4
- two virtualenvs
- run `make dev-mode` in both envs
- craft a config that activates all plugins, see `config.yaml.example`
- start Threat Bus: `venv/bin/threatbus -c config.yaml` in each env (one at a …

Fix thread termination behavior for Python <= 3.7.3

---

apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/vast/setup.py

Fix pyvast-threatbus packaging. There was a malformed entry point in it.
In a virtual env run:
- `make dev-mode`
- `pyvast-threatbus -c apps/vast/config.yaml.example`
- -> should run the app without a startup error about malformed entrypoints

Fix package entry point and imports

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/message_mapping.py
apps/vast/pyvast_threatbus/test_message_mapping.py

This fixes a bug where IoCs with quotes could lead to errors.

Escape backslashes and quotes before querying VAST

---

CHANGELOG.md
plugins/backbones/threatbus_rabbitmq/setup.py
plugins/backbones/threatbus_rabbitmq/threatbus_rabbitmq/rabbitmq_consumer.py

The rewrite in https://github.com/tenzir/threatbus/pull/61 introduced this bug. User-defined queue parameters were not passed to the RabbitMQ host.
This PR shall be released "out-of-band". Note: Our release workflow will trigger once we publish a new release. It will try to re-upload to PyPI and it will fail, because PyPI does not allow the re-use of existing versions but most versions haven't changed. So releasing without bumping all version numbers will color our CI red. It won't affect the correctness of the release, though.
File-by-file.

Fix RabbitMQ user-defined queue parameters

---

tests/utils/misp-ioc-sender/README.md
tests/utils/misp-ioc-sender/config.yaml.example
tests/utils/misp-ioc-sender/misp-ioc-sender.py
tests/utils/misp-ioc-sender/requirements.txt

Add a testing script to inject well-formed `DOMAIN`-type indicators in MISP. The script will create all required resources, if necessary.
- Setup a local MISP instance, e.g., via Docker. You can follow [these instructions](https://github.com/tenzir/threatbus/tree/master/plugins/apps/threatbus_misp#dockerized-misp) in the README of the `threatbus-misp` plugin.
- `cp config.yaml.example config.yaml`
- Place your MISP API key in `config.yaml`
- `pip install -r requirements.txt` (possibly use a virtualenv)
- `python misp-ioc-sender -c config.yaml`
The script logs what it does. You should verify in MISP that an event and attribute have been created. Play around with it, delete or rename resources in MISP, rerun the script. Try to break it.
You can also start Threat Bus with the MISP plugin …

Add misp-ioc-sender test util

---

systemd/README.md

No need to create users when we use `DynamicUser=yes` in the systemd units.

Remove obsolte section from readme

---

apps/vast/CHANGELOG.md
apps/vast/README.md
apps/vast/config.yaml.example
apps/vast/pyvast_threatbus/metrics.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/vast/pyvast_threatbus/test_metrics.py

Collect `min`, `max`, and `avg` metrics for `pyvast-threatbus`. Store to file in configurable interval in [influx line protocol](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/)
Commit-by-commit.
Run the unit-tests.
You can verify locally that metrics are collected by configuring the `metrics` section in your `config.yaml` and sending IoCs to `pyvast-threatbus`.

Collect metrics with pyvast-threatbus

---

tests/utils/misp-ioc-sender/README.md
tests/utils/misp-ioc-sender/config.yaml.example
tests/utils/misp-ioc-sender/misp-ioc-sender.py

Additionally add sightings in MISP testutil.
file-by-file

Add sighting with misp testutil

---

threatbus/threatbus.py

Threat Bus now warns when it finds configuration blocks for plugins that are not installed.
file-by-file.

Warn for configured but uninstalled plugins

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/message_mapping.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/vast/pyvast_threatbus/test_message_mapping.py
apps/vast/setup.py

pyvast-threatbus used to have an optional feature to unflatten JSON that it receives from `vast export`. This is no longer needed as of https://github.com/tenzir/vast/pull/1257. This PR removes the unflatten dependency and all usages in the code.
Commit-by-commit.

Remove unflatten from pyvast-threatbus

---

tests/utils/misp-ioc-sender/misp-ioc-sender.py

* Fix a typo in `tests/utils/misp-ioc-sender/misp-ioc-sender.py` logging an error connecting to MISP instance.
Try to connect to an unreachable MISP instance and confirm correct error message output.

fix typo in logger call

---

.github/workflows/python-egg.yml

https://github.com/mknejp/delete-release-assets
Proposal: delete release assets if they exist before attempting to upload new assets. This is to avoid errors when uploading assets that already exist.
See this run in a repository I created to test these two actions in isolation: https://github.com/0snap/release-action-test/runs/1816583406?check_suite_focus=true

Delete assets before uploading new ones

---

apps/vast/CHANGELOG.md
apps/vast/config.yaml.example
apps/vast/pyvast_threatbus/pyvast_threatbus.py

Allow the user to configure using both, live-matching and retro-matching at the same time for one given IoC.
You can test this interactively as follows:
- Annotate a vast-schema with `#ioc` e.g., the `hostname` field of suricata logs
- Start VAST-Pro 
- Start Threat Bus
- Start `pyvast-threatbus`, change the config so both `live_match` and `retro_match` are set to `true`
- Ingest suricata data into vast, manipulate a hostname
- Inject IoCs into Threat Bus (either via a local MISP instance or by directly injecting into the backbone, e.g., RabbitMQ), use the same hostname you ingested via the logs. That should trigger two things:
- a retro-match
- the IoC is made known to the vast matcher
- ingest the same manipulated log again
- that should trigger a live-match
Note: I did the above on my …

Enable both live- and retro-matching

---

apps/vast/CHANGELOG.md
apps/vast/config.yaml.example
apps/vast/pyvast_threatbus/pyvast_threatbus.py

We used to always pass the `--max-events=` parameter to VAST, regardless of the value of the parameter. Setting it to 0 led to zero results.
This PR enables `pyvast-threatbus to run unlimited queries by setting the `retro_match_max_events` parameter to `0`.
Commit-by-commit

Allow unlimited VAST retro-queries

---

CHANGELOG.md
plugins/apps/threatbus_misp/Makefile
plugins/apps/threatbus_misp/README.md
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_misp/threatbus_misp/plugin.py

Attributes can either be exported from MISP via ZeroMQ or via Kafka. The MISP plugin supports both, but also used to force the user to have both dependencies installed.
This PR eliminates the need to install both dependencies by using [extra dependencies (PEP 508)](https://www.python.org/dev/peps/pep-0508/#extras). This breaks how the plugin is installed:
```
pip install threatbus-misp[zmq]
pip install threatbus-misp[kafka]
```
A plain `pip install threatbus-misp` without specifying the extras option works, but the plugin will throw a critical error during config validation and terminate right after.
Commit-by-commit.

Use optional dependencies for different MISP integrations

---

CHANGELOG.md
Makefile
apps/vast/CHANGELOG.md
apps/vast/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/README.md
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

- Pin versions for different plugins to keep compatibility with older versions installed on PyPI
- Disable `dev-mode` Make target for un-migrated plugins (resp. STIX-2)
This PR is branched off https://github.com/tenzir/threatbus/pull/99 - that has to be merged first.
File-by-file.

Prepare February Release

---

Dockerfile

Disable all plugins that do not yet support STIX-2 in the Dockerfile
File-by-file.
If you like, do a quick `docker build .`.

Disable unmigrated plugins w/o STIX-2 in Dockerfile

---

CHANGELOG.md
Makefile
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_misp/threatbus_misp/message_mapping.py
plugins/apps/threatbus_misp/threatbus_misp/plugin.py
plugins/apps/threatbus_misp/threatbus_misp/test_message_mapping.py
tests/integration/test_misp_inmem.py
tests/utils/zmq_sender.py
threatbus/data.py
threatbus/test_data.py

Following up on the STIX-2 rewrite of Threat Bus: this PR updates the MISP plugin.
- Convert MISP attributes to STIX-2 Indicators
- Convert STIX-2 Sightings to MISP sightings
- New message-passing integration test
- Updated unit tests
- Run the unit-tests (`make dev-mode && make unit-tests`)
- Fire up a local MISP or connect to our testbed and start Threat Bus using this branch
- Click some attributes in the MISP web view
- Send some sightings using our test utils

Rewrite MISP plugin to convert to/from STIX-2 Indicators and Sightings

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/message_mapping.py

This PR introduces a strict equality comparison when mapping Threat Bus IoCs to VAST queries for retro matching.
n/t

Use strict equality comparison in VAST queries

---

Makefile
plugins/apps/threatbus_cif3/README.md
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_cif3/threatbus_cif3/message_mapping.py
plugins/apps/threatbus_cif3/threatbus_cif3/plugin.py

Following up on the STIX-2 rewrite of Threat Bus: this PR updates the CIF3 plugin.
- Convert STIX-2 Indicators to CIF3 Indicators
Code review should be enough as this plugin has seen little attention and there are no unit tests, to begin with.
If you want to test interactively:
- Follow the instructions in the CIF3 plugin's readme to start a CIF3 container and copy the API TOKEN to your Threat Bus `config.yaml`
- Send Indicators via Threat Bus and confirm they make their way into CIF3 (e.g., see the logs)

Rewrite CIF3 plugin to convert STIX-2 Indicators

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/message_mapping.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/vast/pyvast_threatbus/test_message_mapping.py

The VAST matcher is now available as [plugin](https://docs.tenzir.com/vast/features/threat-intel-matching). That rewrite led to a CLI change.
This PR updates `pyvast-threatbus` to use the correct CLI options to work with the VAST matcher plugin. It also fixes a small bug where the wrong function name was called for mapping matcher results to STIX-2 sightings.

Handle VAST matcher CLI changes in pyvast-threatbus

---

apps/vast/CHANGELOG.md
apps/vast/config.yaml.example
apps/vast/pyvast_threatbus/message_mapping.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/vast/pyvast_threatbus/test_message_mapping.py

Add a config option to timeout VAST retro-queries.
File-by-file
Interactively: try setting a small timeout (e.g., 0.1) and verify the query is aborted.

Add timeout option for retro-queries

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/message_mapping.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py
threatbus/data.py

Fix a bug with sighting context post-processing (both custom sinks and context transformation). 
Enable both live- and retro-matching and test interactively by passing sighting context into fever alertify (use example config).

Fix sighting context post-processing

---

CHANGELOG.md
apps/vast/CHANGELOG.md

The categories were inconsistently spelled. Noticed this when going through the release notes.
:shrug:

Fix spelling of changelog categories

---

CHANGELOG.md
apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/message_mapping.py
apps/vast/pyvast_threatbus/test_message_mapping.py
plugins/apps/threatbus_zeek/threatbus_zeek/message_mapping.py
plugins/apps/threatbus_zeek/threatbus_zeek/test_message_mapping.py

- Set `last_seen` correctly with `pyvast-threatbus` and the Zeek plugin
- Fix usage of the `created` timestamp field
- File-by-file.
- Run the unit tests

Properly use the `last_seen` attribute of STIX-2 Sightings

---

CHANGELOG.md
apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/pyvast_threatbus.py
threatbus/threatbus.py

Threat Bus & pyvast-threatbus now require the `-c` / `--config` parameter and print an error message if it Is not provided.
File-by-file.

Print help text when starting without a config file

---

CHANGELOG.md
plugins/apps/threatbus_zmq_app/threatbus_zmq_app/message_mapping.py
plugins/apps/threatbus_zmq_app/threatbus_zmq_app/plugin.py
tests/utils/zmq_receiver.py
threatbus/data.py

Subscribers can now subscribe for multiple Threat Bus topics by sending a single `Subscription` message. That is of advantage to the previous implementation, because subscribers now only get to deal with a single `p2p_topic` for their subscription instead of one `p2p_topic` per subscribed Threat Bus topic.
- Run the integration tests
- Use the `zmq_sender` and `zmq_receiver` in `tests/utils` for interactive testing

Subscribe multiple topics with a single subscription

---

CHANGELOG.md
Makefile
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/Makefile
apps/stix-shifter/README.md
apps/stix-shifter/config.yaml.example
apps/stix-shifter/setup.py
apps/stix-shifter/stix_shifter_threatbus/shifter.py
apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/zmq-app-template/Makefile
apps/zmq-app-template/README.md
apps/zmq-app-template/config.yaml.example
apps/zmq-app-template/setup.py
apps/zmq-app-template/zmq_app_template/template.py

This PR adds a new app that connects with Threat Bus via ZeroMQ and subscribes to the topic `stix2/indicator`. When receiving indicators, the app calls out to the [STIX-Shifter](https://github.com/opencybersecurityalliance/stix-shifter) library to transform the STIX-2 Indicator to a specific query, depending on the user-provided configuration file. Users can configure the `modules` section in the `config.yaml` file. That section instructs the app to call out to certain STIX-Shifter modules, e.g., Splunk or Qradar.
This PR also extracts a template to create Python applications that connect to Threat Bus via ZeroMQ.
_Commit-by-commit_
I tested this interactively with Splunk. The example config works for local Splunk installations. Grab the trial version from the official pages and start it. …

Forward indicators to STIX-Shifter

---

CHANGELOG.md
README.md

This PR changes the chat from Gitter to Slack.
In one scoop.

Change chat from Gitter to Slack

---

apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/stix-shifter/stix_shifter_threatbus/message_mapping.py
apps/stix-shifter/stix_shifter_threatbus/shifter.py
apps/stix-shifter/stix_shifter_threatbus/test_message_mapping.py
apps/vast/setup.py

This PR equips the `stix-shifter-threatbus` app to report back sightings to Threat Bus.
Commit-by-commit.
Interactive: Use the ` tests/utils/zmq_sender.py` test util to send indicators to STIX-Shifter and connect it with e.g., Splunk. Splunk results should find their way back into Threat Bus as STIX-2 Sightings.

Report back Sightings from STIX-Shifter to Threat Bus

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/metrics.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py

Add a new metric type called `InfiniteGauge` to track the size of a growing/shrinking backlog of Indicators that are received by `pyvast-threatbus`, but not yet processed by VAST.
Run the code interactively and verify these metrics are visible in the `metrics.log` file

Collect metrics about received but unprocessed IoCs in pyvast-threatbus

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/message_mapping.py
apps/vast/pyvast_threatbus/test_message_mapping.py

Point queries are much faster than substring queries with VAST, so let's use them here as well to avoid unexpectedly long-running queries.
:shrug:

Use point for URI indicators in pyvast-threatbus

---

.github/workflows/python-egg.yml
CHANGELOG.md
Dockerfile

Update Docker base image and use Debian-maintained Broker libraries for communicating with Zeek.
`docker build . -t foo`
`docker run foo`

Update to Bullseye Docker-base & Debian-maintained Broker libs

---

apps/suricata/CHANGELOG.md
apps/suricata/Makefile
apps/suricata/README.md
apps/suricata/config.yaml.example
apps/suricata/setup.py
apps/suricata/suricata_threatbus/suricata.py

This PR adds a new Python app that connects to Threat Bus via ZeroMQ and listens for STIX-2 indicators with `pattern_type == "suricata"`. Those indicators are then parsed and rule updates are pushed to a suricata rules file, which the user first must configure in their `suricata.yaml` config file.
The app support CUD in a very simplistic, file-based form. We use `suricatasc` to instruct Suricata via its UNIX control socket to re-read the rules from the app-maintained rules file in a configurable interval.
For interactive testing:
- Read the README to prepare your local Suricata
- Start Suricata
- Start OpenCTI
- Start the Threat Bus OpenCTI connector
- Start Threat Bus
- Start the new app (this PR)
- Create new Suricata-typed indicators in OpenCTI (e.g., pattern = `alert http any any -> …

Implement Suricata App for ingesting rules from Threat Bus

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/pyvast_threatbus.py

The current implementation of the metrics value serialization includes spaces into the fields of the measurements, which is not valid according to the spec and will cause the measurement to be rejected. This PR changes this behaviour to ensure all fields are separated by commas.
Compare code and output to line protocol specification.

Fix format of line protocol metrics syntax

---

.github/workflows/python-egg.yml
apps/suricata/CHANGELOG.md
apps/suricata/Dockerfile

- Add Dockerfile and add to release workflow.
Build and run the image.

Release `suricata-threatbus` Docker image together with Threat Bus

---

CHANGELOG.md
Dockerfile
README.md
apps/stix-shifter/Dockerfile
apps/suricata/Dockerfile
apps/vast/Dockerfile

Allows Threat Bus to start in Docker without requiring the user to provide a command. Possible since we have Dynaconf.
Build the image and run it.

Remove Docker entrypoints

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/stix_shifter_threatbus/shifter.py
apps/suricata/CHANGELOG.md
apps/suricata/suricata_threatbus/suricata.py
apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/zmq-app-template/zmq_app_template/template.py
plugins/apps/threatbus_zmq_app/README.md
plugins/apps/threatbus_zmq_app/threatbus_zmq_app/plugin.py
tests/integration/test_zmq_app_management.py

Prior to this change, Threat Bus (the `zmq-app` plugin) returned a wrong  `host:port` tuple to zmq apps. It used to send it's own bind IP address, which is not the same as the IP known to the outside world. Now it only sends the ports for pub/sub and leaves it to the apps to bind to the correct endpoint. 
Run the integration test.
For interactive testing, run all ZMQ apps individually.

Threat Bus zmq apps use the wrong host name after connection.

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/pyvast_threatbus.py

This PR changes the metrics submitted by `pyvast-threatbus` to use the FQDN of the submitting system instead of the short hostname.
Confirm that this change makes sense and is not overly specific.

Use FQDN in pyvast-threatbus metrics

---

apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/pyvast_threatbus.py

Start the measurement of the query time metric together with the actual indicator. This way, we don't skew the metric with indicators that cannot be processed due to user settings for max-background tasks.
n/t

Start measurement of query time metric w/ actual query

---

apps/stix-shifter/setup.py
apps/suricata/setup.py
apps/vast/setup.py
apps/zmq-app-template/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq_app/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
requirements.txt
setup.py

Version 3.0.0 introduced some breaking changes that cause our unit tests to fail with errors like this:
Traceback (most recent call last):
File "/__w/threatbus/threatbus/plugins/apps/threatbus_misp/threatbus_misp/test_message_mapping.py", line 174, in test_valid_stix_sighting
misp_sighting = stix2_sighting_to_misp(self.sighting)
File "/__w/threatbus/threatbus/plugins/apps/threatbus_misp/threatbus_misp/message_mapping.py", line 329, in stix2_sighting_to_misp
if "x_threatbus_source" in sighting.object_properties():
File "/usr/local/lib/python3.9/dist-packages/stix2/base.py", line 269, in __getattr__
raise AttributeError(
AttributeError: 'Sighting' object has no attribute 'object_properties'

Pin version 2.x of stix2 package

---

CHANGELOG.md
README.md
apps/stix-shifter/Makefile
apps/suricata/Makefile
apps/suricata/config.yaml.example
apps/suricata/suricata_threatbus/suricata.py
apps/vast/Makefile
apps/vast/config.yaml.example
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/zmq-app-template/Makefile
config.yaml.example
plugins/apps/threatbus_cif3/threatbus_cif3/plugin.py
plugins/apps/threatbus_misp/threatbus_misp/plugin.py
plugins/apps/threatbus_zeek/threatbus_zeek/plugin.py
plugins/backbones/threatbus_rabbitmq/threatbus_rabbitmq/plugin.py
threatbus/threatbus.py

This PR allows users to omit more config values in the threatbus config.
- Only load configured plugins
- Provide more default values
- Update documentation with default values

Allow omitting more config values

---

CHANGELOG.md
apps/vast/CHANGELOG.md
apps/vast/pyvast_threatbus/message_mapping.py
apps/vast/pyvast_threatbus/pyvast_threatbus.py
apps/vast/pyvast_threatbus/test_message_mapping.py

Support for VAST live matching was broken due to some syntax adjustments introduced with the recent matcher rewrite.
This PR reintroduces live matching support by slightly adjusting the way we interact with the matcher from Threat Bus.

Add support for VAST live matching to threatbus

---

CHANGELOG.md
config.yaml.example
plugins/apps/threatbus_misp/threatbus_misp/plugin.py

The 'apps.misp.api' key is optional, but the code used to assume
that if it is present, then all three of the subkeys 'api.host',
'api.ssl' and 'api.key' are also present.
We now validate that this is indeed the case.
Try providing an invalid MISP config and verify that threatbus doesn't start and doesn't crash with an unhandled exception.

Correctly validate 'apps.misp.api.*' config settings

---

apps/stix-shifter/setup.py
apps/suricata/setup.py
apps/suricata/suricata_threatbus/suricata.py
apps/vast/setup.py
apps/vast/vast_threatbus/test_message_mapping.py
apps/vast/vast_threatbus/vast_threatbus.py
apps/zmq-app-template/setup.py
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_cif3/threatbus_cif3/message_mapping.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_misp/threatbus_misp/message_mapping.py
plugins/apps/threatbus_misp/threatbus_misp/test_message_mapping.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zeek/threatbus_zeek/message_mapping.py
plugins/apps/threatbus_zeek/threatbus_zeek/test_message_mapping.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
requirements.txt
tests/integration/test_zeek_app.py

The `StixBase::object_properties()` method [was removed](https://github.com/oasis-open/cti-python-stix2/commit/2cda97cf5e51403c43a96ceb9073afab7706638a) in stix 3.0 on charges of being obsolete, breaking our code.
This PR removes the calls to `object_properties()` analogous to how it was done in the linked upstream PR, and bumps the minimum dependency version to 3.0 since making these changes will break compatibility with stix 2.x,

Unpin stix2 and fix breaking changes

---

CHANGELOG.md
requirements.txt
setup.py
threatbus/threatbus.py

The release of pluggy 1.0 broke threatbus, since we use
type annotations for our arguments and the module containing
the _HookRelay class was renamed from `pluggy.hooks`
to `pluggy._hooks`.

Update codebase for pluggy 1.0

---

CHANGELOG.md
apps/stix-shifter/CHANGELOG.md
apps/stix-shifter/setup.py
apps/suricata/CHANGELOG.md
apps/suricata/setup.py
apps/vast/CHANGELOG.md
apps/vast/setup.py
apps/zmq-app-template/setup.py
docker/vast-threatbus/Dockerfile
plugins/apps/threatbus_cif3/setup.py
plugins/apps/threatbus_misp/setup.py
plugins/apps/threatbus_zeek/setup.py
plugins/apps/threatbus_zmq/setup.py
plugins/backbones/file_benchmark/setup.py
plugins/backbones/threatbus_inmem/setup.py
plugins/backbones/threatbus_rabbitmq/setup.py
setup.py

This is mostly a maintenance release; just dependency changes and updating the Dockerfile to today's VAST release to keep everything synchronized.

Prepare repository for Threat Bus 2021.09.30

---

CHANGELOG.md
apps/vast/vast_threatbus/vast_threatbus.py

`vast-threatbus` now uses the `low-priority` option if supported by the vast instance.

Use low-priority exports if available

---

requirements.txt
setup.py
threatbus/threatbus.py

This PR removes the requirement for a specific pre- or post-1.0 version of the `pluggy` dependency to allow interoperability with older versions.
I have tested this successfully in a virtualenv with 0.13.1 and 1.0.0. If you can imagine other cases worthy of testing, feel free to go on.

Make Threat Bus independent of pluggy versions

---

plugins/apps/threatbus_misp/threatbus_misp/message_mapping.py

This PR fixes an issue in the MISP plugin where filters with orgids would cause MISP indicators not to be filtered correctly. This is because orgids in the filter are parsed to integers internally by the config engine, but the MISP JSON presents the corresponding value as a string, causing a check to never succeed. This is addressed by interpreting the string value from MISP as an integer (which is expected)  and comparing that. We keep the original string comparison to allow string values in the filter config to still match, for whatever reason they might appear.
No special instructions.

Correctly compare orgids between filter and MISP

---

CHANGELOG.md
apps/vast/CHANGELOG.md
apps/vast/vast_threatbus/message_mapping.py
apps/vast/vast_threatbus/vast_threatbus.py
threatbus/data.py

Add a new '%matchtype' variable to transform_context in vast-threatbus 

---

shell.nix

Poetry2nix normalises names internally, and these are the names that are set in the respective `pyproject.toml` files.
This PR also depends on https://github.com/nix-community/poetry2nix/pull/486.

shell.nix: Set correct editable sources names
